name: Build on Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Visual Studio
      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: 2019 # Ensure this matches the version used to build MinHook

      # Step 3: Build the project
      - name: Build HaloCEVR
        run: |
          msbuild HaloCEVR.sln /p:Configuration=Release /p:Platform=x86

      # Step 4: Run tests (if applicable)
      # Add test steps here if you have any tests to run

      # Step 5: Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: HaloCEVR/Release