name: Build on Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Configure project
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build project
        run: |
          cd build
          make

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/
