name: Build on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bootstrap
        run: ./bootstrap-vcpkg.sh

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make