name: Build on Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up dependencies
      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Step 3: Build project
      - name: Build project
        run: |
          make

      # Step 4: Run tests
      - name: Run tests
        run: |
          make test

      # Step 5: Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./ # Adjust path to match where your build outputs are located
