name: Build on Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Visual Studio
      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1

      # Step 3: Build the project using the CI-specific configuration
      - name: Build HaloCEVR
        run: |
          msbuild HaloCEVR.sln /p:Configuration=CI_Release /p:Platform=x86 /p:WholeProgramOptimization=false

      # Step 4: Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: HaloCEVR
          path: HaloCEVR.zip

      # Step 5: Comment on the PR with the artifact link
      - name: Comment on PR with artifact link
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context, github } = require('@actions/github');
            const artifactUrl = `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`
            await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `The build artifacts are available [here](${artifactUrl}).`
            })