name: Build HaloCEVR

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup vcpkg
        run: |
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg.exe install

      - name: Build MinHook
        run: |
          git clone https://github.com/TsudaKageyu/minhook
          cd minhook\build\VC17
          msbuild MinHook.sln /p:Configuration=Release /p:Platform=x86

      - name: Copy MinHook library
        run: |
          copy minhook\build\VC17\Release\libMinHook.x86.lib HaloCEVR-master\ThirdParty\MinHook\lib\libMinHook.x86.lib

      - name: Build HaloCEVR
        run: |
          msbuild HaloCEVR.sln /p:Configuration=Release /p:Platform=x86

      - name: Package Release
        run: |
          .\makerelease.bat
          # Ensure openvr_api.dll is in the release folder or handle it manually