name: Build on Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Visual Studio
      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1

      # Step 3: Build the project using the CI-specific configuration
      - name: Build HaloCEVR
        run: |
          msbuild HaloCEVR.sln /p:Configuration=CI_Release /p:Platform=x86 /p:WholeProgramOptimization=false

      # Step 4: Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: HaloCEVR
          path: CI_Release